"""Standalone static server for the frontend, so it runs independently of the
API.

    python -m tools.serve_frontend

Reads FRONTEND_HOST / FRONTEND_PORT / VAHAN_API_BASE from `.env`. If
VAHAN_API_BASE is set, `/config.js` is generated on the fly with that value
(overriding frontend/config.js) so the backend URL lives entirely in `.env`.
"""
from __future__ import annotations

import functools
import http.server
import json
from pathlib import Path

from backend.settings import settings  # loads .env

FRONTEND_DIR = Path(__file__).resolve().parent.parent / "frontend"


class Handler(http.server.SimpleHTTPRequestHandler):
    def end_headers(self) -> None:  # no caching while developing
        self.send_header("Cache-Control", "no-store")
        super().end_headers()

    def do_GET(self) -> None:  # noqa: N802
        if self.path.split("?")[0] == "/config.js" and settings.api_base:
            body = (
                "/* generated by tools/serve_frontend.py from VAHAN_API_BASE */\n"
                f"window.__VAHAN_CONFIG__ = {{ API_BASE: {json.dumps(settings.api_base)} }};\n"
            ).encode()
            self.send_response(200)
            self.send_header("Content-Type", "application/javascript; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(body)
            return
        super().do_GET()


def main() -> None:
    if not FRONTEND_DIR.is_dir():
        raise SystemExit(f"frontend directory not found: {FRONTEND_DIR}")
    handler = functools.partial(Handler, directory=str(FRONTEND_DIR))
    httpd = http.server.ThreadingHTTPServer((settings.frontend_host, settings.frontend_port), handler)
    where = f"http://{settings.frontend_host}:{settings.frontend_port}"
    api = settings.api_base or "(from frontend/config.js)"
    print(f"frontend  ->  {where}")
    print(f"API_BASE  ->  {api}")
    print("Ctrl+C to stop")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        httpd.shutdown()


if __name__ == "__main__":
    main()
